### ISSUE TITLE
Download many videos with URLs from a file

### ISSUE THREAD

**Issue by gioluca2** [trahay/bbb-downloader#16]
Hi,
can you add multiple downloads from .txt files input?

Thanks
Regards

**Comment by trahay** [comment]
Hi,
I added this possibility (cf commit #0c7847f ). You can now call `capture-full-replay.sh` with an input file:

```
$ cat input_file.txt
https://bbb-node.imtbs-tsp.eu/playback/presentation/2.0/playback.html?meetingId=fb8a9cb664e003d61d06e6c7f71196fb9b2c0922-1588707575341 video1.mp4
https://bbb-node.imtbs-tsp.eu/playback/presentation/2.0/playback.html?meetingId=fb8a9cb664e003d61d06e6c7f71196fb9b2c0922-1588666735451 video2.mp4
$ ./capture-full-replay.sh -i input_file.txt
Downloading https://bbb-node.imtbs-tsp.eu/playback/presentation/2.0/playback.html?meetingId=fb8a9cb664e003d61d06e6c7f71196fb9b2c0922-1588707575341, and saving it as video1.mp4
[...]
Downloading https://bbb-node.imtbs-tsp.eu/playback/presentation/2.0/playback.html?meetingId=fb8a9cb664e003d61d06e6c7f71196fb9b2c0922-1588666735451, and saving it as video2.mp4
[...]
```

**Comment by gioluca2** [comment]
Thank you very much.
Can I set higher resolution and h.264 main profile?
After a download I have only 520 pixels like vertical resolution and I can open the file only with vlc (due to high 4:4:4 profile).
I can convert them manually with commamd "ffmpeg -i input.mp4 -profile:v main -pix_fmt yuv420p out.mp4" to solve the issue, but can you do anything while downloading?
