### ISSUE TITLE
I do not seem to be able to install the python requirements

### ISSUE THREAD

**Issue by me7pako** [trahay/bbb-downloader#22]
I tried implementing the steps mentioned in the readme section, after I reach the "pip3 install -r python-requirements.txt" command, I get the following error: 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'python-requirements.txt'
I have Ubuntu 20.04.2 LTS.
Any solution guys ?
Thanks in advance.

**Comment by wolbernd** [comment]
@me7pako This looks more like a file system permission issue. Please check that the user that runs pip3 has at least read permissions on the requirements file.

**Comment by trahay** [comment]
Another possibility is that @me7pako has an "old" version of bbb-downloader that needs to be updated. python-requirements.txt was added recently (january, 17th), so you may need to run `git pull` first.

**Comment by me7pako** [comment]
Alright guys thnks a bunch.
I guess I am still a noob since I needed to do other things before I could run the commands you provided.
Now it is running but the download has a problem. I will be posting the problem in another issue if you would allow.
