### ISSUE TITLE
Problem when integrating soundtrack

### ISSUE THREAD

**Issue by dvdsosa** [trahay/bbb-downloader#24]
Hi all,

When integrating soundtrack by ./integrate_soundtrack command, I get an error from ffmpeg.

First, I download:
`./download_bbb_data.py https://bbb-aep2.ulpgc.es/playback/presentation/2.0/playback.html\?meetingId\=bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868`

Then, I integrate soundtrack:
`./integrate_soundtrack.sh bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos last
`
And I get:
```
# Extracting sound from bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/webcams.webm to bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/output.opus
# running ffmpeg -i bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/webcams.webm -vn -acodec copy bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/output.opus
# Merging video (bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/deskshare.webm) and audio (bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/output.opus) into last
# Running ffmpeg -i bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/deskshare.webm -i bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos/output.opus -map 0:v -map 1:a -c copy -y last
Failed !
```

Can anyone help?
thanks!

**Comment by trahay** [comment]
The problem here is that the `last` parameter to `integrate_soundtrack.sh` must be a file with an extension that ffmpeg can produce (eg. `.webm` or `.mp4`). You can fix that by running:
```
./integrate_soundtrack.sh bbb32bb487132b4493676126412c2a4c2d37771e-1614796183868/Videos last.mp4
```

**Comment by dvdsosa** [comment]
Great! 

I just read the README.md and followed the instructions. Maybe for other people, noting the necessity to add such extension would be helpful, i.e.:

`./integrate_soundtrack.sh Videos [output_file].[ext]`

Thanks for your work trahay !

**Comment by trahay** [comment]
Good idea ! I updated the README.md.
