### ISSUE TITLE
Error no module named 'numpy'

### ISSUE THREAD

**Issue by bsr126** [trahay/bbb-downloader#27]
getting error while downloading file. Check the screenshot

![Screenshot 2021-08-06 115549](https://user-images.githubusercontent.com/9985544/128466020-fe4e229d-0c1f-46c7-9233-5f7547286bd6.png)

**Comment by trahay** [comment]
Hi,
This should be fixed by running the following  command:
```
pip3 install -r python-requirements.txt
```

François
