### ISSUE TITLE
New URL?

### ISSUE THREAD

**Issue by risturiz** [trahay/bbb-downloader#29]
Hi, i was using this script to download and make mp4 recordings from openstreetmap bbb server https://osmvideo.cloud68.co ... Now i cant download videos ( maybe url change? )... Last video have this link:

https://osmrecordings.cloud68.co/playback/presentation/2.3/2ed32e8865ca5e0a7690b4727eefcd01c4a6540b-1643466260318

Thanks for any help.

**Comment by trahay** [comment]
Hi,
The link you provide works fine with bbb-downloader on my laptop. Can you send us the output generated by `capture-full-replay.sh` ? 

François

**Comment by risturiz** [comment]
Hi, i was using download_bbb_data.py ... I can try with capture-full-replay.sh and share results... Thanks!

**Comment by risturiz** [comment]
Hi again... I can confirm that "capture-full-replay.sh" work BUT the result is not the complete video, only 8:49 minutes were saved.

**Comment by trahay** [comment]
Hi,
I fixed the detection of the duration of videos (see commit #503474d) and it should work now.
In case of a problem, you can also pass the `-e X` option to `capture-full-replay.sh` to specify the duration you want to capture.

**Comment by risturiz** [comment]
Thanks! Now the download is complete without issue

**Comment by muhammadk1607** [comment]
@risturiz  you should close this issue then

**Comment by risturiz** [comment]
You are right @MBM1607 ... Fixed
