### ISSUE TITLE
Add a way to crop the full replay capture to the window contents only

### ISSUE THREAD

**Issue by olberger** [trahay/bbb-downloader#4]
The capture of the replays made with Selenium captures the whole of the X display, including the Firefox windows, decorations, etc.

Unfortunately, there doesn't seem to be a way to switch the Firefox window contents to fullscreen with the Selenium marionette driver (or I haven't check well).

An option would then be to automatically crop the video to only deliver the inner part of the window.
Haven't investigated the post-processing options.

Of course, there would also be a need for cutting start/end of screen capture.

**Comment by trahay** [comment]
I added the `crop_video.sh` script that can be called to remove the firefox window. By default, it also removes the first seconds of the captured video (when the firefox window is loading).

An option for this script allows to capture only the main screen  in case the webcam was disabled when recording.
