### ISSUE TITLE
Add documentation on what URL to pass

### ISSUE THREAD

**Issue by guerby** [trahay/bbb-downloader#5]
The following doesn't seem to work (URL from the bbb regular web viewer):

`./bbb_downloader.sh 'https://bbb.some.where/playback/presentation/2.0/playback.html?meetingId=xxx-yyy`

What URL should be provided to bbb_downloader.sh ?

**Comment by trahay** [comment]
I agree that the script should use this URL. Currently, it uses the base URL for the video files :
`./bbb_downloader.sh https://bbb.some.where/presentation/xxx-yyy` (where `xxx-yyy` is the meeting id)

I'll fix the URL detection soon.

**Comment by olberger** [comment]
Or try ```capture-full-replay.sh https://bbb.some.where/playback/presentation/2.0/playback.html?meetingId=xxx-yyy``` ;-)

**Comment by trahay** [comment]
This should be fixed by commit 7d76881

**Comment by trahay** [comment]
I did a few more changes on this.
You can now use `download_bbb_data.py` to download the videos (along with other data captured by BBB such as the slides), and merge the sound track and the deskshare with using  the `integrate_soundtrack.sh` script.
