### ISSUE TITLE
error 2626 promise js

### ISSUE THREAD

**Issue by Lutice** [trahay/bbb-downloader#9]
Hello
If you have this error :

```
node_modules/selenium-webdriver/lib/promise.js:2626                                                                                                     │ 0%
        throw error;
        ^
ElementNotInteractableError: Element <button class="acorn-play-button"> could not be scrolled into view
```
it's because the browser didn't display the replay  page, you need to increase the delay before record and wait the replay page is correctly show, just increase this parameter in the file selenium-play-bbb-recording.js on line 35

`driver.sleep(1000 * 4);`
Regards
Fabrice

**Comment by olberger** [comment]
How long was necessary for it to work on your side ? Could you suggest a better defaults ?

We can adjust that delay to a longer one by default, and adjust the replay capture duration too, as a consequence. 10 more seconds wouldn't harm in general, given it's basically slow in all cases...

**Comment by olberger** [comment]
Maybe there's a smarter way requiring to wait for the page readiness in the Selenium script, but I haven't had time to dig into this yet.
Again, I'm not sure I'll have time to dedicate on this, so any patches welcome.

**Comment by Lutice** [comment]
Yes I suggested a better defaults it's 1000 * 4 against 1000 * 2

**Comment by olberger** [comment]
Sorry, my bad. I had overlooked our own defaults being 2 ;)
